In [1]:
import numpy as np

In [3]:
a = np.array([2,5,4,7,9])
a

array([2, 5, 4, 7, 9])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

1

In [7]:
a.shape

(5,)

In [20]:
m = np.array([4,8,3,6,3,5,6,8,9,2,3,4.5]).reshape(4, -1)

m

array([[4. , 8. , 3. ],
       [6. , 3. , 5. ],
       [6. , 8. , 9. ],
       [2. , 3. , 4.5]])

In [21]:
m.shape

(4, 3)

In [22]:
m.dtype

dtype('float64')

#### Indexing & slicing

In [23]:
a

array([2, 5, 4, 7, 9])

In [26]:
a[2:4]

array([4, 7])

In [27]:
m

array([[4. , 8. , 3. ],
       [6. , 3. , 5. ],
       [6. , 8. , 9. ],
       [2. , 3. , 4.5]])

In [30]:
m[-1]

array([2. , 3. , 4.5])

In [32]:
m[-1, 2]

np.float64(4.5)

In [34]:
m[2, 1]

np.float64(8.0)

In [35]:
m[1:3]

array([[6., 3., 5.],
       [6., 8., 9.]])

In [36]:
m[1:3, 1:]

array([[3., 5.],
       [8., 9.]])

In [37]:
m

array([[4. , 8. , 3. ],
       [6. , 3. , 5. ],
       [6. , 8. , 9. ],
       [2. , 3. , 4.5]])

In [43]:
a

array([2, 5, 4, 7, 9])

In [44]:
a[[2, 0, 4]]

array([4, 2, 9])

In [56]:
m[[3,2,1]]

array([[2. , 3. , 4.5],
       [6. , 8. , 9. ],
       [6. , 3. , 5. ]])

array([2, 5, 4, 7, 9])

In [58]:
a * 100

array([200, 500, 400, 700, 900])

In [62]:
a % 3 == 0

array([False, False, False, False,  True])

In [65]:
a[a % 2 == 0] * 2

array([4, 8])

In [66]:
a[a > 6]

array([7, 9])

In [71]:
np.square(a)

array([ 4, 25, 16, 49, 81])

In [76]:
a

array([2, 5, 4, 7, 9])

In [74]:
b = np.array([1,0,1,0,1])
b

array([1, 0, 1, 0, 1])

In [77]:
a + b

array([ 3,  5,  5,  7, 10])

In [78]:
np.random.randint(1, 100, 20)

array([63, 93, 57, 99, 26,  6, 21, 67, 98, 36, 14, 95, 49, 45,  2, 48,  7,
       54, 55, 42])

In [82]:
data = np.random.normal(10, 2, 1000)

In [84]:
print( 'mean:', np.mean(data) )
print( 'std:', np.std(data) )
print( 'min:', np.min(data) )
print( 'max:', np.max(data) )

mean: 10.162137075818308
std: 1.9570651936825874
min: 4.449853766383945
max: 16.233267550199315


In [85]:
data.mean()

np.float64(10.162137075818308)

In [86]:
q1, q3 = np.quantile(data, [0.25, 0.75])

iqr = q3 - q1

print(q1)
print(q3)
print(iqr)

8.861469368206095
11.394298967551274
2.5328295993451793


In [87]:
lower_limit = q1 - 1.5 * iqr
upper_limit = q3 + 1.5 * iqr

print(lower_limit)
print(upper_limit)

5.062224969188326
15.193543366569042


In [89]:
is_outlier = (data < lower_limit) | (data > upper_limit)

outliers = data[is_outlier]
outliers

array([ 4.54959235, 15.43178613, 15.94903749, 16.23326755,  4.96353204,
       15.37587271,  4.44985377, 15.58591744, 15.57109186])

In [92]:
clean = data[~is_outlier].copy()

In [93]:
clean.shape

(991,)